# Generated by Django 5.2.5 on 2025-08-19 15:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='marks',
            name='exam_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
