# Generated by Django 5.2.5 on 2025-08-15 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_alter_student_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='student',
            unique_together={('student_class', 'roll_no')},
        ),
    ]
